2025-03-16 11:43:06 ERROR    not enough values to unpack (expected 4, got 1)
Traceback (most recent call last):
  File "c:\Users\external\Desktop\M1S2\PLDAC\SEM\module\test_dataload.py", line 92, in <module>
    main(params)
  File "c:\Users\external\Desktop\M1S2\PLDAC\SEM\module\test_dataload.py", line 29, in main
    train_dataset = SEMdataset(args, "KG_train.txt", e2id, r2id, t2id, c2id, 'train')
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\external\Desktop\M1S2\PLDAC\SEM\module\dataloader.py", line 20, in __init__
    self.data = self.load_dataset()
                ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\external\Desktop\M1S2\PLDAC\SEM\module\dataloader.py", line 39, in load_dataset
    mask_ent, et_triples, kg_triples, clu_triples = [_.strip() for _ in line.split('|||')]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 1)
